# Dependencies
markdown:         kramdown
highlighter:      rouge

kramdown:
  auto_ids: true

# Permalinks
permalink:        pretty

# Server
source:          ./src/docs
destination:     ./docs
keep_files:		 ['assets', 'libs', 'javascripts', 'stylesheets']
host:             0.0.0.0
port:             9001
baseurl:          ""
# url:              http://getbootstrap.com
encoding:         UTF-8

# Custom vars
current_version:  0.1.0
repo:             https://github.com/skywalkplugins/bootstrap-quick-search

vendor:			  ./vendor
download:
  source:         https://github.com/skywalkplugins/bootstrap-quick-search/archive/master.zip
#   dist:           https://github.com/twbs/bootstrap/releases/download/v4.0.0-alpha/bootstrap-4.0.0-alpha-dist.zip